# Generated by Django 6.0.1 on 2026-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электроная почта')),
                ('code', models.CharField(max_length=4)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
