# Generated by Django 6.0.1 on 2026-01-16 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=150, verbose_name='Локация')),
                ('is_online', models.BooleanField(default=False, verbose_name='Действует')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('basket', 'Basket'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='basket', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Бронирования',
                'verbose_name_plural': 'Бронирование',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('student', 'Student')], default='standard', max_length=20)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('total_quantity', models.IntegerField(verbose_name='Общее количество')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
            options={
                'verbose_name': 'Тип билета',
                'verbose_name_plural': 'типы билетов',
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tickettype')),
            ],
            options={
                'verbose_name': 'Элемент бронирования',
                'verbose_name_plural': 'Элементы бронирования',
            },
        ),
    ]
