# Generated by Django 6.0.1 on 2026-01-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_booking_event_alter_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together={('booking', 'ticket_type')},
        ),
    ]
